typedef unsigned char   undefined;

typedef unsigned char    byte;
typedef unsigned int    dword;
typedef unsigned long    qword;
typedef unsigned char    undefined1;
typedef unsigned short    word;
typedef struct btl_enemy btl_enemy, *Pbtl_enemy;

struct btl_enemy {
    pointer enemy_type;
    pointer field_0x8;
    int field_0x10;
    int field_0x14;
    int ring_section;
    int line_section;
    int field_0x20;
    int field_0x24;
    int field_0x28;
    int field_0x2c;
    pointer circle;
    int field_0x38;
    int field_0x3c;
};

typedef struct setdata setdata, *Psetdata;

struct setdata {
    pointer s_setData_battle_W5C3;
    pointer field_0x8;
    pointer field_0x10;
    int field_0x18;
    int field_0x1c;
    int field_0x20;
    int field_0x24;
    int field_0x28;
    int field_0x2c;
    int field_0x30;
    int field_0x34;
    int field_0x38;
    int field_0x3c;
    int field_0x40;
    int field_0x44;
    int field_0x48;
    int field_0x4c;
    int field_0x50;
    int field_0x54;
    int field_0x58;
    int field_0x5c;
    int field_0x60;
    int field_0x64;
    int field_0x68;
    int field_0x6c;
    int field_0x70;
    int field_0x74;
    int field_0x78;
    int field_0x7c;
    int field_0x80;
    int field_0x84;
    int field_0x88;
    int field_0x8c;
    pointer field_0x90;
    pointer field_0x98;
    int field_0xa0;
    int field_0xa4;
    int field_0xa8;
    int field_0xac;
    pointer field_0xb0;
    int field_0xb8;
    int field_0xbc;
    int field_0xc0;
    int field_0xc4;
    int field_0xc8;
    int field_0xcc;
    int field_0xd0;
    int field_0xd4;
    int field_0xd8;
    int field_0xdc;
    int field_0xe0;
    int field_0xe4;
    int field_0xe8;
    int field_0xec;
    int field_0xf0;
    int field_0xf4;
    int field_0xf8;
    int field_0xfc;
    int field_0x100;
    int field_0x104;
    int field_0x108;
    int field_0x10c;
    int field_0x110;
    int field_0x114;
    int field_0x118;
    int field_0x11c;
};

