typedef unsigned char   undefined;

typedef unsigned char    byte;
typedef unsigned int    dword;
typedef unsigned long    qword;
typedef unsigned char    undefined1;
typedef unsigned short    word;
typedef struct hand hand, *Phand;

struct hand {
    pointer s_disposHand;
    undefined * field_0x8;
    int field_0x10;
    int field_0x14;
    undefined * field_0x18;
    undefined * field_0x20;
    undefined * field_0x28;
    undefined * field_0x30;
    undefined * field_0x38;
    int field_0x40;
    int field_0x44;
    int field_0x48;
    int field_0x4c;
    int field_0x50;
    int field_0x54;
    float field_0x58;
    float field_0x5c;
    float field_0x60;
    int field_0x64;
    int field_0x68;
    int field_0x6c;
    int field_0x70;
    float field_0x74;
    float field_0x78;
    float field_0x7c;
    float field_0x80;
    int field_0x84;
    int field_0x88;
    int field_0x8c;
    int field_0x90;
    float field_0x94;
    int field_0x98;
    int field_0x9c;
    int field_0xa0;
    float field_0xa4;
    int field_0xa8;
    int field_0xac;
    float field_0xb0;
    int field_0xb4;
    int field_0xb8;
    int field_0xbc;
    undefined * field_0xc0;
    undefined * field_0xc8;
    undefined * field_0xd0;
    undefined * field_0xd8;
    int field_0xe0;
    int field_0xe4;
    int field_0xe8;
    int field_0xec;
    int field_0xf0;
    int field_0xf4;
    pointer field_0xf8;
    int field_0x100;
    int field_0x104;
    int field_0x108;
    int field_0x10c;
    int field_0x110;
    int field_0x114;
    float field_0x118;
    int field_0x11c;
};

